services:
  # Identity Provider using Duende IdentityServer
  identityserver:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - ../identityserver:/src
    ports:
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5002
      - ConnectionStrings__DefaultConnection=Server=db;Database=RqmtMgmtIdentity;User=sa;Password=Your_password123;TrustServerCertificate=True;
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:5002", "--project", "/src/identityserver.csproj"]
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          memory: 1G

  frontend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - ../frontend:/src
    expose:
      - "5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OIDC__Authority=https://rqmtmgmt.local
      - OIDC__ClientId=rqmtmgmt-frontend
      - OIDC__ClientSecret=frontend-secret
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:5001"]
    depends_on:
      backend:
        condition: service_healthy
      identityserver:
        condition: service_started
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          memory: 1G

  backend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - ../backend:/src
    expose:
      - "5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=RqmtMgmt;User=sa;Password=Your_password123;TrustServerCertificate=True;
      - Authentication__Authority=https://rqmtmgmt.local
      - Authentication__Audience=rqmtmgmt-api
      - Authentication__RequireHttpsMetadata=false
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:5000", "--project", "/src/backend.csproj"]
    depends_on:
      db:
        condition: service_healthy
      identityserver:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          memory: 2G

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-identity.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server-cert.pem:/etc/ssl/certs/server-cert.pem:ro
      - ./certs/server-key.pem:/etc/ssl/private/server-key.pem:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy
      identityserver:
        condition: service_started

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      # Configure SQL Server memory settings for Docker
      MSSQL_MEMORY_LIMIT_MB: "2048"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 3G
        reservations:
          memory: 2G

volumes:
  sqlvolume: