# Override configuration for systems with limited memory
# This reduces resource allocation for all services
services:
  frontend:
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M

  backend:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  db-test:
    environment:
      # Further reduce SQL Server memory for constrained systems
      MSSQL_MEMORY_LIMIT_MB: "512"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

  nginx:
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 128M
