services:
  frontend:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - ../frontend:/src
      - ../local_nuget:/src/local_nuget
      - ../nuget.config:/src/nuget.config
    expose:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:80", "--project", "/src/frontend.csproj"]
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    working_dir: /src
    volumes:
      - ../backend:/src
      - ../local_nuget:/src/local_nuget
      - ../nuget.config:/src/nuget.config
    expose:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=RqmtMgmt;User=sa;Password=Your_password123;TrustServerCertificate=True;
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:80", "--project", "/src/backend.csproj"]
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "timeout 10s bash -c '</dev/tcp/localhost/1433' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s

volumes:
  sqlvolume: